# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
pod 'SwiftKeychainWrapper', '~> 4.0'

  # Pods for demo

end
